FROM azul/zulu-openjdk:17-latest
ENV PROJ_HOME=/root/work/habr-tg-bot
ENV SPRING_PROFILES_ACTIVE=prod
ENV DB_PASSWORD=$DB_PASSWORD
ENV HABR_TG_BOT_TOKEN=$HABR_TG_BOT_TOKEN
ENV REPORTING_TG_BOT_USER_ID=$REPORTING_TG_BOT_USER_ID
COPY . $PROJ_HOME
WORKDIR $PROJ_HOME
RUN chmod +x ./sh/build-and-run.sh
ENTRYPOINT ["./sh/build-and-run.sh"]