spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/habrbot
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
bot:
  name: "HabrViewBot"
  token: "1874857108:AAFSbnTJ8sADfORvJ4HSCnokT_i8D4cq6jg"
  last-post-url: ""
  scheduled:
    update: 1000
    new-posts: 60000