spring:
  datasource:
    url: jdbc:postgresql://localhost/habrbot
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate